### ISSUE TITLE
Output 'points' or json structure to determine position of the rooms on output images?

### ISSUE THREAD

**Issue by Baaleos** [OndrejNepozitek/ProceduralLevelGenerator#44]
Use case:
Online roguelike / mud style game - On my overworld (1000x1000 grid) - every 5x5 pixel is a cell- I use this to navigate and draw players position on world map.

I was hoping to use this library for drawing maps for interior areas - such as castles etc.
Instead of drawing a 5x5 pixel of where they are - Now I would simply highlight the room that they are in. 
In order to do that- I need to be able to translate Room 1 - into an array of points that correspond with the corners of that room.

Any ideas how to do this with the outputs currently provided?

**Comment by OndrejNepozitek** [comment]
Hey,
the output of the algorithm is a list of `IRoom` instances with `GridPolygon Shape { get; }` and `IntVector2 Position { get; }` properties.  `GridPolygon` has `GetPoints()` method that returns a set of points that define the polygon room - these should be the corners you are looking for. Now if you add the `Position` to the corners of the room, you get the final position of the room in the image.

```csharp
var layout = // Generate layout

foreach (var room in layout.Rooms) {
  foreach (var point in room.Shape.GetPoints()) {
    var imageCornerPosition = point + room.Position;
  }
}
```

If you use the json output, it is quite similar. Instead of using `Shape.GetPoints()`, the points are save directly in the `Shape` property. And there is also a `Position` that you add to the points.

Is that what you need?

**Comment by Baaleos** [comment]
thanks for getting back - now that you have explained it - it looks promising.
Currently getting to grips with the library's basic functionality.
